version: '3.8'

services:
  datacenter-panel:
    image: ghcr.io/cristhian-sancore/painel-2.0/datacenter-panel:latest
    container_name: datacenter-panel
    restart: unless-stopped
    ports:
      - "3001:3000"

    environment:
      - NODE_ENV=production
      - EVOLUTION_API_KEY=sancore_evolution_master_key_123
      - CHATWOOT_API_URL=https://chatwoot2.cristhiansancore.com.br
      - CHATWOOT_ACCESS_TOKEN=WGMzdQwPraor579LG7o9NRcm
      - INSTALLATION_KEY=sancore_setup_key_2026
